AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/EndOfLine:
  Enabled: False



Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'
